<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-S2R2BFT" failures="1" tests="4" name="testNgStudy.ListenerClass1_TC1" time="0.023" errors="0" timestamp="2024-01-06T14:14:37 IST" skipped="1">
  <testcase classname="testNgStudy.ListenerClass1_TC1" name="a" time="0.002">
    <system-out>
      <![CDATA[Test Case a execution start
Hi a is running
Test Case a completed successfully]]>
    </system-out>
  </testcase> <!-- a -->
  <testcase classname="testNgStudy.ListenerClass1_TC1" name="b" time="0.018">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testNgStudy.ListenerClass1_TC1.b(ListenerClass1_TC1.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
    <system-out>
      <![CDATA[Test Case b execution start
Test Case b is fail Please check again]]>
    </system-out>
  </testcase> <!-- b -->
  <testcase classname="testNgStudy.ListenerClass1_TC1" name="c" time="0.001">
    <skipped/>
    <system-out>
      <![CDATA[Test Case c is skipped please check dependent method]]>
    </system-out>
  </testcase> <!-- c -->
  <testcase classname="testNgStudy.ListenerClass1_TC1" name="d" time="0.002">
    <system-out>
      <![CDATA[Test Case d execution start
Hi d is running 
Test Case d completed successfully]]>
    </system-out>
  </testcase> <!-- d -->
  <system-out>
    <![CDATA[Test Case b execution start
Test Case b is fail Please check again
Test Case d execution start
Hi d is running 
Test Case d completed successfully
Test Case a execution start
Hi a is running
Test Case a completed successfully
Test Case c execution start
Test Case c is skipped please check dependent method
Test Case f execution start
Hi f is running
Test Case f completed successfully
Test Case g execution start
Hi g is running 
Test Case g completed successfully
Test Case i execution start
Hi i is running 
Test Case i completed successfully
Test Case h execution start
Test Case h is fail Please check again]]>
  </system-out>
</testsuite> <!-- testNgStudy.ListenerClass1_TC1 -->
